delete from core.nucleo_basico_conocimiento;
delete from core.area_conocimiento;
delete from core.tipo_dato_adicional;
delete from core.periodo;
delete from core.tipo_periodo;
delete from core.unidad_tiempo
delete from core.concepto_academico;
delete from core.linea_investigacion_grupo_investigacion;
delete from core.grupo_investigacion;
delete from core.linea_investigacion;