swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /periodo/:
    get:
      tags:
      - periodo
      description: get Periodo
      operationId: PeriodoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Periodo'
        "404":
          description: not found resource
    post:
      tags:
      - periodo
      description: create Periodo
      operationId: PeriodoController.Post
      parameters:
      - in: body
        name: body
        description: body for Periodo content
        required: true
        schema:
          $ref: '#/definitions/models.Periodo'
      responses:
        "201":
          description: '{int} models.Periodo'
        "400":
          description: the request contains incorrect syntax
  /periodo/{id}:
    get:
      tags:
      - periodo
      description: get Periodo by id
      operationId: PeriodoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Periodo'
        "404":
          description: not found resource
    put:
      tags:
      - periodo
      description: update the Periodo
      operationId: PeriodoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Periodo content
        required: true
        schema:
          $ref: '#/definitions/models.Periodo'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Periodo'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - periodo
      description: delete the Periodo
      operationId: PeriodoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /tipo_dato_adicional/:
    get:
      tags:
      - tipo_dato_adicional
      description: get TipoDatoAdicional
      operationId: TipoDatoAdicionalController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDatoAdicional'
        "404":
          description: not found resource
    post:
      tags:
      - tipo_dato_adicional
      description: create TipoDatoAdicional
      operationId: TipoDatoAdicionalController.Post
      parameters:
      - in: body
        name: body
        description: body for TipoDatoAdicional content
        required: true
        schema:
          $ref: '#/definitions/models.TipoDatoAdicional'
      responses:
        "201":
          description: '{int} models.TipoDatoAdicional'
        "400":
          description: the request contains incorrect syntax
  /tipo_dato_adicional/{id}:
    get:
      tags:
      - tipo_dato_adicional
      description: get TipoDatoAdicional by id
      operationId: TipoDatoAdicionalController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDatoAdicional'
        "404":
          description: not found resource
    put:
      tags:
      - tipo_dato_adicional
      description: update the TipoDatoAdicional
      operationId: TipoDatoAdicionalController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TipoDatoAdicional content
        required: true
        schema:
          $ref: '#/definitions/models.TipoDatoAdicional'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDatoAdicional'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - tipo_dato_adicional
      description: delete the TipoDatoAdicional
      operationId: TipoDatoAdicionalController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /tipo_periodo/:
    get:
      tags:
      - tipo_periodo
      description: get TipoPeriodo
      operationId: TipoPeriodoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoPeriodo'
        "404":
          description: not found resource
    post:
      tags:
      - tipo_periodo
      description: create TipoPeriodo
      operationId: TipoPeriodoController.Post
      parameters:
      - in: body
        name: body
        description: body for TipoPeriodo content
        required: true
        schema:
          $ref: '#/definitions/models.TipoPeriodo'
      responses:
        "201":
          description: '{int} models.TipoPeriodo'
        "400":
          description: the request contains incorrect syntax
  /tipo_periodo/{id}:
    get:
      tags:
      - tipo_periodo
      description: get TipoPeriodo by id
      operationId: TipoPeriodoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoPeriodo'
        "404":
          description: not found resource
    put:
      tags:
      - tipo_periodo
      description: update the TipoPeriodo
      operationId: TipoPeriodoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TipoPeriodo content
        required: true
        schema:
          $ref: '#/definitions/models.TipoPeriodo'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoPeriodo'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - tipo_periodo
      description: delete the TipoPeriodo
      operationId: TipoPeriodoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /unidad_tiempo/:
    get:
      tags:
      - unidad_tiempo
      description: get UnidadTiempo
      operationId: UnidadTiempoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.UnidadTiempo'
        "404":
          description: not found resource
    post:
      tags:
      - unidad_tiempo
      description: create UnidadTiempo
      operationId: UnidadTiempoController.Post
      parameters:
      - in: body
        name: body
        description: body for UnidadTiempo content
        required: true
        schema:
          $ref: '#/definitions/models.UnidadTiempo'
      responses:
        "201":
          description: '{int} models.UnidadTiempo'
        "400":
          description: the request contains incorrect syntax
  /unidad_tiempo/{id}:
    get:
      tags:
      - unidad_tiempo
      description: get UnidadTiempo by id
      operationId: UnidadTiempoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.UnidadTiempo'
        "404":
          description: not found resource
    put:
      tags:
      - unidad_tiempo
      description: update the UnidadTiempo
      operationId: UnidadTiempoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for UnidadTiempo content
        required: true
        schema:
          $ref: '#/definitions/models.UnidadTiempo'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.UnidadTiempo'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - unidad_tiempo
      description: delete the UnidadTiempo
      operationId: UnidadTiempoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
definitions:
  models.Periodo:
    title: Periodo
    type: object
    properties:
      Activo:
        type: boolean
      Ano:
        type: string
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      NumeroOrden:
        type: number
        format: double
      Periodo:
        type: string
      TipoPeriodo:
        $ref: '#/definitions/models.TipoPeriodo'
  models.TipoDatoAdicional:
    title: TipoDatoAdicional
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.TipoPeriodo:
    title: TipoPeriodo
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.UnidadTiempo:
    title: UnidadTiempo
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
tags:
- name: unidad_tiempo
  description: |
    UnidadTiempoController operations for UnidadTiempo
- name: tipo_dato_adicional
  description: |
    TipoDatoAdicionalController operations for TipoDatoAdicional
- name: periodo
  description: |
    PeriodoController operations for Periodo
- name: tipo_periodo
  description: |
    TipoPeriodoController operations for TipoPeriodo
